name: Release Windows

# Start on tag push (ex v1.0.0)
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  compile_pipeline_and_release:
    runs-on: windows-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v7

      - name: Set Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Make
        run: choco install make

      - name: Setup python
        working-directory: ./src
        shell: bash
        run: cp "$(which python)" "$(dirname "$(which python)")/python3.11.exe"

      - name: Setup pipeline python
        working-directory: ./src
        run: make pipeline_python-setup SHELL=cmd.exe

      - name: compile pipeline
        working-directory: ./src
        run: make compile-pipeline SHELL=cmd.exe

      - name: Clean pipeline python setup
        working-directory: ./src/main
        shell: bash
        run: rm -r pediatric_fdopa_pipeline

      - name: copy the folder and zip
        shell: bash
        run: |
          FOLDER_NAME="GliAAns-${{ github.ref_name }}-main-windows"
          cp -r src/main "$FOLDER_NAME"
          
          7z a "$FOLDER_NAME.zip" "$FOLDER_NAME"
          
      - name: Create release and upload asset
        uses: softprops/action-gh-release@v2
        with:
          files: GliAAns-${{ github.ref_name }}-main-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
