name: Release Linux

# Start on tag push (ex v1.0.0)
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  compile_pipeline_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v7

      - name: Imposta Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Setup pipeline python
        working-directory: ./src
        run: |
          make pipeline_python-setup

      - name: compile pipeline
        working-directory: ./src
        run: |
          make compile-pipeline

      - name: Clean pipeline python setup
        working-directory: ./src/main
        run: |
          rm -r pediatric_fdopa_pipeline

      - name: Prepara la cartella ed effettua lo ZIP
        run: |
          FOLDER_NAME="GliAAns-${{ github.ref_name }}-main-linux"

          cp -r src/main "$FOLDER_NAME"

          zip -r "$FOLDER_NAME.zip" "$FOLDER_NAME"

      - name: Crea la Release e carica l'Asset
        uses: softprops/action-gh-release@v2
        with:
          files: GliAAns-${{ github.ref_name }}-main-linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
